In [2]:
import numpy as np
from numpy.matlib import zeros

## Data Types and Attributes

In [3]:
# numpy main data type is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        
        [
           [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)

a3.shape

(3, 2, 3)

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating array

In [11]:
sample_array = np.array([1, 2, 3])

In [12]:
ones = np.ones((3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[7, 8, 1, 6, 1],
       [3, 4, 2, 1, 8],
       [6, 5, 8, 4, 0]])

In [18]:
random_array_2 = np.random.random((3,5,2))
random_array_2

array([[[0.9490539 , 0.80813704],
        [0.35525889, 0.96038493],
        [0.64635477, 0.4245883 ],
        [0.57559669, 0.00723876],
        [0.1580174 , 0.21717921]],

       [[0.631525  , 0.55913429],
        [0.71082929, 0.25226749],
        [0.11045929, 0.67662101],
        [0.94419049, 0.8651948 ],
        [0.80545283, 0.17733967]],

       [[0.52245723, 0.32372627],
        [0.56341734, 0.78393509],
        [0.28125111, 0.27277567],
        [0.39506926, 0.32506942],
        [0.88209295, 0.86002418]]])

In [19]:
random_array_3 = np.random.rand(3,5,2)
random_array_3

array([[[0.06119521, 0.84819401],
        [0.50391805, 0.39898256],
        [0.1009878 , 0.86929388],
        [0.95745701, 0.34775933],
        [0.4444169 , 0.92513278]],

       [[0.81266222, 0.60605908],
        [0.3408399 , 0.16621648],
        [0.59856952, 0.41958769],
        [0.35743764, 0.87675302],
        [0.28583133, 0.88179429]],

       [[0.14547784, 0.57754152],
        [0.64802764, 0.87381661],
        [0.61197006, 0.21493036],
        [0.29307945, 0.71521096],
        [0.23779558, 0.14288915]]])

In [20]:
random_array_4 = np.random.randint(10, size=(3,5))
random_array_4

array([[5, 5, 1, 4, 6],
       [1, 7, 1, 3, 2],
       [7, 8, 9, 4, 4]])

## 3 viewing array and matrices

In [21]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
random_array_3[0]

array([[0.06119521, 0.84819401],
       [0.50391805, 0.39898256],
       [0.1009878 , 0.86929388],
       [0.95745701, 0.34775933],
       [0.4444169 , 0.92513278]])